---
- name: Add cloudadmins group
  group:
    name: "{{ cloudadmins_group }}"

- name: Add users to cloudadmins and wheel groups
  user:
    name: "{{ item.name }}"
    groups: "{{ item.group }},wheel"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: ~/.ssh/id_rsa
    ssh_key_comment: "{{ item.name }}@{{ inventory_hostname }}"
  loop: "{{ users }}"

- name: Distribute SSH keys for users
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  loop: "{{ users }}"

